fallback-grpc-addr: 127.0.0.1:3030

jaeger:
  url: "http://127.0.0.1:14268/api/traces"


order:
  service_name: order
  server_to_run: http
  http-addr: 127.0.0.1:8282
  grpc-addr: 127.0.0.1:5002

stock:
  service_name: stock
  server_to_run: grpc
  http-addr: 127.0.0.1:8283
  grpc-addr: 127.0.0.1:5003

payment:
  service_name: payment
  server_to_run: http
  http-addr: 127.0.0.1:8284
  grpc-addr: 127.0.0.1:5004

consul:
  addr: 127.0.0.1:8500

rabbitmq:
  user: guest
  password: guest
  host: 127.0.0.1
  port: 5672
  max-retry: 3

mongo:
  user: root
  password: password
  host: 127.0.0.1
  port: 27017
  db-name: "order"
  coll-name: "order"

redis:
  local:
    ip: 127.0.0.1
    port: 6379
    pool_size: 100
    max_conn: 100
    conn_timeout: 1000
    read_timeout: 1000
    write_timeout: 100

mysql:
  user: root
  password: root
  host: localhost
  port: 3307
  dbname: "gorder"


# Linux 下的stripe-key: "${STRIPE_KEY}"
# Windows 下的
stripe-key: "STRIPE_KEY"

# Linux 下 endpoint_stripe_secret: "${ENDPOINT_STRIPE_SECRET}"
endpoint.stripe_secret: "ENDPOINT_STRIPE_SECRET"

dial-grpc-timeout: 10